lua/gp.lua

Hi, I have a scratch file fold and I want to put the chat files along with my other scratch files.
So I hope this GpChatResponse can be triggered outside the chat fold.
For example, in my usecase, the file is `/Users/lintao/.cache/nvim/scratch.nvim/192326-230723.gp.md`

Allow GpChatResponse be triggered by files not in the chat folder

---

README.md
lua/gp/init.lua

Motivation:
Most user hooks primarily generate responses in Markdown style, not just code. Therefore, I think it would be useful if the response is correctly formatted in the Markdown buffer instead *.cpp or another file types.
If such a solution is unacceptable, then we can create something like `target.enewMarkdown` or a similar to resolve this issue.

feat: Convert M.Target.enew to function

---

lua/gp/init.lua

Makes sure number formatting of `sox`'s output uses decimal point on all systems regardless of their locale by setting `LC_NUMERIC='C'`.

fix: proper number formatting for sox (resolve: Robitx/gp.nvim#77)

---

README.md
lua/gp/config.lua
lua/gp/health.lua
lua/gp/init.lua

Add `env` is also unsafe. 
If users use password managers like 1Password or Bitwarden, they can get the api key by running some system command. 
For example `bw get password chatgpt-api-key`.
This pr adds one new config option to supplement methods getting `the KEY`.

Add one new secure way to get  the api key. 

---

doc/gp.txt

Hi
This is a very nice plugin, probably the best LLM integration I've seen so far.
One thing that it is currently missing is documentation, so I asked GPT-4 Turbo to generate it. The promt was:
```
This is the code for a Neovim Lua plugin. Please generate a Vim documentation for the plugin (should be a text file in the format expected by vim):
(then pasted the code for init.lua)
```
This is what it generated. Not sure if it is very accurate, but maybe we can use as a starting point (feel free to push changes to this PR).

Add documentation

---

lua/gp/init.lua

hey there!
thank you for this superb plugin, it's extremely useful!
i had a small issue with undoing changes done in insert mode and took
few minutes to fix it.
Not sure if it's the best way to fix it, and i haven't thoroughly tested
all features (there're a lot!).
`gp.nvim` has autosave feature which is triggered by few events, one of which is `TextChangedI`.
when typing text in insert mode, any change done there saves the file. This grows the `:undolist` too much, because any change in insert mode is saved and treated as a separate change.
Normally to undo the last change, you would press `u` once in normal mode. But with autosave triggered by `TextChangedI`, you have to press `u` multiple times, for each change.
using `InsertLeave` instead of `TextChangedI` avoids such problem.
For …

chore: use `InsertLeave` instead of `TextChangedI`

---

lua/gp/config.lua
lua/gp/init.lua

Hello and thanks for the plugin! I had a little issue getting whisper to work, so submitting a fix your consideration.
This PR adds a way to manually specify in the config which command (`sox`, `ffmpeg`, or `arecord`) should be used for recording for commands like `GpWhisper`. E.g. use it in `.setup()` like `whisper_rec_cmd = 'sox'`.
I had an issue trying to use `GpWhisper`, where the output would always be just "you". I found the recordings, `rec.wav`, were always the correct length, but only silence. I think the problem is the options to `ffmpeg` select audio input device `:0`, which doesn't work in my case. Modifying `gp/init.lua` to always choose `rec_cmd = "sox"` works fine for me. There's probably some way to look into the audio input devices more and improve the autodetection, but …

Add option to set whisper recording command

---

lua/gp/init.lua

I noticed that the info-msgs on creating new directories always require user input (press enter) and that a warning pops up if the state file is not found. Both of these are annoying on fresh installations of the plugin (something I do a lot).
This PR fixes both of these issues, please have a look.

Avoid needing user input on fresh installations

---

lua/gp/config.lua

This pull request introduces updates to the default model configurations in the `config.lua` file to leverage the latest versions of OpenAI's models. Specifically, the `gpt-4o` model has replaced the previous `gpt-4-1106-preview` model, and the `gpt-3.5-turbo` model has replaced the `gpt-3.5-turbo-1106` model. These changes have been applied across various sections of the configuration to ensure consistency and improved performance.
The primary motivation for this update is to take advantage of the enhanced capabilities and optimizations available in the latest model versions. By transitioning to `gpt-4o` and `gpt-3.5-turbo`, users can expect more accurate and efficient AI responses, whether they are engaging in chat-based interactions or utilizing the models for command-based tasks. …

feat: update defaults to use latest model versions for gpt-4 and gpt-3.5

---

lua/gp/init.lua

Empty lines as paragraph separators are quite common in ChatGPT's responses. But in most cases we don't want them in the search results. Although they disappear on a simple search of any char, removing them makes the picker window look more compact on startup.
| Before | After |
| - | - |
| ![image](https://github.com/Robitx/gp.nvim/assets/71320000/8006a097-fd0b-499f-8b67-5c85433836a2) | ![image](https://github.com/Robitx/gp.nvim/assets/71320000/35804b94-7737-4e44-bb3a-b4dd92481ee7) |

feat: filter out empty lines from picker window

---

README.md
doc/gp.nvim.txt
lua/gp/config.lua
lua/gp/init.lua

Found a few places that used bellow instead of below and corrected them.
Thanks for all the work on this plugin!

Fix spelling of the word bellow to below

---

.editorconfig
README.md
lua/gp/init.lua

so this can be changed on the fly.
Ideally I would like to be able to pass it an existing file too but I wanted to do a minimum first contribution. Also I develop on top of https://github.com/Robitx/gp.nvim/pull/93 which doesn't help

make it possible tu use :GpWhisper <LANGUAGE>

---

README.md
lua/gp/config.lua
lua/gp/init.lua

With multi provider support gp.Prompt got a bit unwieldy and causes bugs like #147, #149, #154.
The gp.cmd.ChatNew used to make chats for specific task (like dedicated translator) didn't take providers into account at all.

feat: improve/simlify gp.Prompt and gp.cmd.ChatNew function signatures

---

lua/gp/config.lua
lua/gp/defaults.lua

When adding your own agents, you have to provide default prompts. Let's expose gp.nvim's default ones t avoid the user troubling him/herself with the issue.
the "default" in names might be redundant.

feat: expose default_(chat|code)_system_prompt to user

---

lua/gp/init.lua

I am using the power of gp.nvim to generate a Git commit message after the response is complete.
To do this, I added the `on_complete_callback` argument to the `M.Prompt` and `M.query` functions.
I am a new Neovim user and very new to Lua script. This is my 1st PR.  Feedback is welcome.
Below is an example of how I setup the git commit function.
```lua
hooks = {
GitCommitStaged = function(gp, params)
local system_prompt =
"You are a commit title generator. You use the GPT-4 version of OpenAI's GPT models. You must only provide the commit title. Rules to follows: Write commit title for the change with commitizen convention. Make sure the title has maximum 50 characters. You must not provide additional explination/description other than the git commit title."
local prompt =
"Below is the …
```

feat: add on_complete_callback to gp.Prompt

---

lua/gp/init.lua

Hello. Thanks for the great plugin. Pretty minor change, but this allows the use of openrouter without requiring somebody to specify their openai provider should be openrouter and complicating access to the other aspects of openai's ecosystem. If I need to edit it to flesh out openrouter support as an option, I can. But really it just needs the header defined. Also happy to consider other options.

feat: added headers for openrouter

---

README.md
doc/gp.nvim.txt
lua/gp/config.lua
lua/gp/init.lua
lua/gp/logger.lua

feat: add logging to file

---

lua/gp/init.lua

Made the provider header thingy fallback to the openai compatible header so that it works with any compatible API (e.g. groq). I left the original `openai` case because of the backwards compatible `api-key` header.

Default to openai compatible headers

---

lua/gp/init.lua

When deleting a chat, if any path component in `config.chat_dir` is a symlink, the following sanity check fails:
```lua
if not _H.starts_with(file_name, M.config.chat_dir) then
M.logger.warning("File " .. vim.inspect(file_name) .. " is not in chat dir")
return
end
```
This causes the GpChatDelete command to always fail in such cases.
Resolve `chat_dir` symlinks when performing the sanity check.

Fixes bug deleting chat file when config.chat_dir contains a symlink

---

lua/gp/init.lua

Capture the preceding parameters for `ChatRespond`
I hope to be able to obtain input parameters before using the command.，This can better coordinate with the use of keymap.
For example, when I input `1<c-g><c-g>`, it can send a question in a new chat.

Capture the preceding parameters for ChatRespond

---

lua/gp/init.lua

Symbolic links cannot be created using the `ln` command in Windows.
I will use New-Item in PowerShell to create a symbolic link.
This will solve #176 issue.

Create Sysbolic link for Windows

---

lua/gp/dispatcher.lua

For OpenAI-compatible endpoints, the plugin doesn't pass the max_tokens parameter.

add max_tokens to payload

---

lua/gp/config.lua
lua/gp/init.lua

A straightforward trick to make the configuration options could be auto-completion

docs: expose `GpConfig`

---

lua/gp/config.lua
lua/gp/init.lua

This PR proposes changing the default shortcut in GpFinder to provide a more user-friendly experience when managing GpChat markdown history. The current prefix keybinding, <c-g>d, may be cumbersome for some users. This update will allow users to assign different keybindings to GPFinder, enhancing flexibility. Implementing this change will make the interface more accessible and customizable, potentially increasing user efficiency and satisfaction.

add a keybinding config for ChatFinder

---

lua/gp/dispatcher.lua

o series of models supports streaming now
add support for o3 reasoning model
use [`reasoning_effort`](https://platform.openai.com/docs/api-reference/chat/create#chat-create-reasoning_effort) property from model on o3 series of models (defaults to "medium", other options being "low" and "high")
Closes [245](https://github.com/Robitx/gp.nvim/issues/245)

add o3 support

---

lua/gp/dispatcher.lua

The o1-preview and o1-mini models can be used with copilot provider when you have a copilot pro subscription. This ensures the request/response are handled in those cases (currently only openai provider is handled).

feat: handle o1 when used with copilot provider

---

lua/gp/config.lua

This PR updates how we specify the Anthropic Claude model version. Instead of using a hardcoded date (20240620), we now use the "latest" identifier to always get the most up-to-date version of Claude.

feat: update Claude model versions to latest

---

lua/gp/config.lua

This PR updates the Copilot configuration to use `apps.json` instead of `hosts.json` for OAuth token extraction, restoring Copilot functionality in the `gp.nvim` plugin.

Rename hosts.json to apps.json for Copilot secret configuration

---

README.md
doc/gp.nvim.txt
lua/gp/init.lua

This PR adds the `:GpSelectAgent` command, providing a more intuitive way to switch between AI agents when you have multiple models configured.
- **`:GpSelectAgent` command**: Opens a selection interface using `vim.ui.select` to choose from all available agents
- **Context-aware selection**: Automatically shows chat agents when in a chat buffer, command agents otherwise
- **Current agent highlighting**: The currently active agent is marked with "(current)" for easy identification
- **Telescope integration**: Works seamlessly with telescope.nvim if available, providing fuzzy search capabilities
- **Better UX for many models**: Instead of cycling through agents one by one with `:GpNextAgent`, users can now see all options and directly select their desired model
Run `:GpSelectAgent` or use …

feat: add :GpSelectAgent to improve selection of agents

---

lua/gp/whisper.lua

When whisper sends the transcribe request the content-type was missing from the file parameter.
That caused some transcription endpoints to not correctly recognize the content type audio/mpeg.

fix: setting content type of mp3 file in whisper transcribe
